/*
 * Tablewise — desk.cjs
 * Author: Fiifi Kaasiebrew (https://github.com/fiifikaasiebrew)
 * Copyright (c) 2026 Fiifi Kaasiebrew. All rights reserved.
 */
const Module = require('module'); const path = require('path'); const fs = require('fs'); const os = require('os');
const handlers = {}; const ud = fs.mkdtempSync(path.join(os.tmpdir(), 'twud'));
const fake = { app: { getPath: () => ud, requestSingleInstanceLock: () => false, quit() {}, on() {}, whenReady: () => new Promise(() => {}), getVersion: () => '1' }, ipcMain: { handle: (c, f) => handlers[c] = f }, dialog: {}, safeStorage: { isEncryptionAvailable: () => false }, shell: {}, Menu: { buildFromTemplate: () => ({}) }, net: {}, BrowserWindow: function () {} };
const orig = Module._load; Module._load = function (r, ...a) { return r === 'electron' ? fake : orig.call(this, r, ...a); };
process.chdir(path.join(__dirname, '../desktop'));
require(path.join(__dirname, '../desktop/main.js'));
const call = async (ch, ...a) => { const r = await handlers[ch](null, ...a); if (!r.ok) throw new Error(ch + ': ' + r.error); return r.v; };
const DDL = {
  postgres: [`DROP TABLE IF EXISTS orders; DROP TABLE IF EXISTS customers;`, `CREATE TABLE customers (id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, name VARCHAR(255) NOT NULL, email VARCHAR(255) UNIQUE, credit NUMERIC(12,2), active BOOLEAN DEFAULT TRUE)`, `CREATE TABLE orders (id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, customer_id INTEGER NOT NULL, placed DATE, FOREIGN KEY (customer_id) REFERENCES customers(id))`],
  mysql: [`DROP TABLE IF EXISTS orders; DROP TABLE IF EXISTS customers;`, 'CREATE TABLE customers (id INT AUTO_INCREMENT PRIMARY KEY, name VARCHAR(255) NOT NULL, email VARCHAR(255) UNIQUE, credit DECIMAL(12,2), active TINYINT(1) DEFAULT 1)', 'CREATE TABLE orders (id INT AUTO_INCREMENT PRIMARY KEY, customer_id INT NOT NULL, placed DATE, FOREIGN KEY (customer_id) REFERENCES customers(id))'],
  sqlite: ['CREATE TABLE customers (id INTEGER PRIMARY KEY AUTOINCREMENT, name TEXT NOT NULL, email TEXT UNIQUE, credit NUMERIC(12,2), active INTEGER DEFAULT 1)', 'CREATE TABLE orders (id INTEGER PRIMARY KEY AUTOINCREMENT, customer_id INTEGER NOT NULL, placed DATE, FOREIGN KEY (customer_id) REFERENCES customers(id))']
};
(async () => {
  const file = path.join(ud, 'test.sqlite');
  const cfgs = [{ kind: 'sqlite', file, create: true }, { kind: 'postgres', host: '127.0.0.1', port: 5432, database: 'twdb', user: 'tw', password: 'tw' }, { kind: 'mysql', host: '127.0.0.1', port: 3306, database: 'twdb', user: 'tw', password: 'tw' }];
  for (const cfg of cfgs) {
    try {
      const q = cfg.kind === 'mysql' ? '`' : '"';
      const { id, name } = await call('db:connect', cfg);
      for (const d of DDL[cfg.kind]) await call('db:query', id, d, []);
      await call('db:transaction', id, [{ sql: `INSERT INTO ${q}customers${q} (${q}name${q}, ${q}email${q}, ${q}credit${q}) VALUES (?, ?, ?), (?, ?, ?)`, params: ['Ama\'s Shop ? yes', 'a@x.com', 10.5, 'Kofi', 'k@x.com', 99] }]);
      await call('db:query', id, `INSERT INTO ${q}orders${q} (${q}customer_id${q}, ${q}placed${q}) VALUES (?, ?)`, [1, '2026-09-01']);
      const r = await call('db:query', id, `SELECT * FROM ${q}customers${q} WHERE ${q}name${q} ${cfg.kind === 'postgres' ? 'ILIKE' : 'LIKE'} ? ORDER BY ${q}id${q} LIMIT 50`, ['%shop%']);
      const upd = await call('db:query', id, `UPDATE ${q}customers${q} SET ${q}credit${q} = ? WHERE (${q}id${q} = ?)`, [12.25, 2]);
      let fkErr = ''; try { await call('db:query', id, `DELETE FROM ${q}customers${q} WHERE (${q}id${q} = ?)`, [1]); } catch (e) { fkErr = e.message.slice(0, 70); }
      let txErr = ''; try { await call('db:transaction', id, [{ sql: `INSERT INTO ${q}customers${q} (${q}name${q}) VALUES (?)`, params: ['X'] }, { sql: `INSERT INTO ${q}customers${q} (${q}name${q}) VALUES (?)`, params: [null] }]); } catch (e) { txErr = 'rolled back'; }
      const cnt = await call('db:query', id, `SELECT COUNT(*) FROM ${q}customers${q}`, []);
      const tabs = await call('db:listTables', id);
      const d = await call('db:describe', id, 'orders'); const dc = await call('db:describe', id, 'customers');
      console.log(`\n== ${cfg.kind} (${name})`);
      console.log(' select:', JSON.stringify(r.columns), JSON.stringify(r.rows));
      console.log(' update changes:', upd.changes, '| fk delete error:', fkErr, '| tx:', txErr, '| count after failed tx:', cnt.rows[0][0]);
      console.log(' tables:', JSON.stringify(tabs));
      console.log(' orders key:', d.key, 'fks:', JSON.stringify(d.fks), 'cust cols:', dc.columns.map(c => `${c.name}:${c.type}${c.pk ? ':pk' : ''}${c.auto ? ':auto' : ''}${c.unique ? ':uniq' : ''}${c.notnull ? ':nn' : ''}`).join(' '));
      const multi = await call('db:query', id, `SELECT 1 AS a; SELECT 2 AS b`, []);
      console.log(' multi sets:', multi.sets.length, JSON.stringify(multi.rows));
      if (cfg.kind === 'sqlite') { const snap = await call('db:snapshot', id); await call('db:query', id, 'DELETE FROM orders', []); await call('db:restore', id, snap); console.log(' restore -> orders:', (await call('db:query', id, 'SELECT COUNT(*) FROM orders', [])).rows[0][0]); }
      await call('db:close', id);
      if (cfg.kind === 'sqlite') console.log(' file size on disk:', fs.statSync(file).size);
    } catch (e) { console.log(cfg.kind, 'FAILED', e.message); }
  }
  const saved = await call('conn:save', { kind: 'postgres', host: 'h', port: 1, database: 'd', user: 'u', password: 'secret', remember: true });
  console.log('\nsaved conn:', JSON.stringify(await call('conn:list')));
  console.log('params mssql:', require(path.join(__dirname, '../desktop/main.js')).convertParams("SELECT '?' , [a?] FROM t WHERE x = ? AND y = ? -- ?", 'mssql'));
  process.exit(0);
})();
