/*
 * Tablewise — sql-library.js
 * Author: Fiifi Kaasiebrew (https://github.com/fiifikaasiebrew)
 * Copyright (c) 2026 Fiifi Kaasiebrew. All rights reserved.
 */
/* The SQL function library: every entry explained simply, with an example that runs on the practice data.
   ex is either one string (works everywhere) or {sqlite, postgres, mysql, mssql, all}. "LIMIT n" at the end is
   turned into TOP n for SQL Server automatically. */
const SQL_CATS = ['Picking data', 'Filtering', 'Sorting and paging', 'Totals and groups', 'Joining tables', 'Text', 'Numbers and maths', 'Dates and times', 'Conditions', 'Combining results', 'Subqueries and WITH', 'Window functions', 'Changing data', 'Table design', 'Transactions', 'Types and info'];
const SQL_LIB = [
  // ---------- Picking data
  ['Picking data', 'SELECT *', 'Show every column of a table.', 'SELECT * FROM table_name', 'SELECT * FROM customers LIMIT 10'],
  ['Picking data', 'SELECT columns', 'Show only the columns you name, in the order you name them.', 'SELECT column1, column2 FROM table_name', 'SELECT company_name, city, country FROM customers LIMIT 10'],
  ['Picking data', 'AS (rename)', 'Give a column a friendlier name in the answer. The table itself does not change.', 'SELECT column AS new_name', 'SELECT company_name AS customer, city AS town FROM customers LIMIT 10'],
  ['Picking data', 'DISTINCT', 'Show each different value only once, like a list of all the cities without repeats.', 'SELECT DISTINCT column FROM table_name', 'SELECT DISTINCT country FROM customers ORDER BY country'],
  ['Picking data', 'Maths on columns', 'Work out a new value from other columns, like quantity times price.', 'SELECT column_a * column_b AS result', 'SELECT order_id, quantity, unit_price, quantity * unit_price AS line_total FROM order_items LIMIT 10'],
  ['Picking data', 'Fixed values', 'Add a column that says the same thing on every row.', "SELECT column, 'text' AS label", "SELECT company_name, 'customer' AS kind FROM customers LIMIT 10"],
  // ---------- Filtering
  ['Filtering', 'WHERE =', 'Keep only rows where a column equals a value. Text goes in single quotes.', "WHERE column = 'value'", "SELECT * FROM customers WHERE city = 'Accra'"],
  ['Filtering', '<> (not equal)', 'Keep rows where a column is anything except this value.', "WHERE column <> 'value'", "SELECT * FROM orders WHERE status <> 'delivered' LIMIT 20"],
  ['Filtering', '> < >= <=', 'Bigger than, smaller than, at least, at most. Works on numbers and dates.', 'WHERE column >= number', 'SELECT name, unit_price FROM products WHERE unit_price >= 15 ORDER BY unit_price'],
  ['Filtering', 'AND', 'Both rules must be true.', 'WHERE rule1 AND rule2', "SELECT * FROM customers WHERE country = 'Ghana' AND segment = 'Retail'"],
  ['Filtering', 'OR', 'At least one of the rules must be true.', 'WHERE rule1 OR rule2', "SELECT * FROM customers WHERE city = 'Accra' OR city = 'Kumasi'"],
  ['Filtering', 'NOT', 'Flip a rule around: keep the rows where it is false.', 'WHERE NOT rule', "SELECT * FROM orders WHERE NOT status = 'cancelled' LIMIT 20"],
  ['Filtering', 'Brackets ( )', 'Decide which rules go together, like in maths.', 'WHERE (rule1 OR rule2) AND rule3', "SELECT * FROM customers WHERE (city = 'Accra' OR city = 'Kumasi') AND segment = 'Retail'"],
  ['Filtering', 'IN', 'Keep rows whose value is in your list. Shorter than lots of ORs.', "WHERE column IN ('a', 'b', 'c')", "SELECT * FROM customers WHERE city IN ('Accra', 'Lagos', 'Nairobi')"],
  ['Filtering', 'NOT IN', 'Keep rows whose value is not in your list.', "WHERE column NOT IN ('a', 'b')", "SELECT * FROM orders WHERE status NOT IN ('delivered', 'cancelled')"],
  ['Filtering', 'BETWEEN', 'Keep values from one number or date up to another, including both ends.', 'WHERE column BETWEEN low AND high', "SELECT * FROM orders WHERE order_date BETWEEN '2026-01-01' AND '2026-03-31'"],
  ['Filtering', 'LIKE with %', 'Search inside text. % means "anything can go here".', "WHERE column LIKE '%word%'", "SELECT * FROM customers WHERE company_name LIKE '%Foods%'"],
  ['Filtering', 'LIKE with _', '_ means "exactly one character goes here".', "WHERE column LIKE 'NW-10_0'", "SELECT sku, name FROM products WHERE sku LIKE 'NW-10_0'"],
  ['Filtering', 'Starts with / ends with', "Put % on one side only. 'A%' starts with A, '%Ltd' ends with Ltd.", "WHERE column LIKE 'A%'", "SELECT company_name FROM customers WHERE company_name LIKE '%Ltd'"],
  ['Filtering', 'IS NULL', 'Find rows where nothing was written in a column. (= NULL never works, you must use IS NULL.)', 'WHERE column IS NULL', 'SELECT * FROM orders WHERE employee_id IS NULL'],
  ['Filtering', 'IS NOT NULL', 'Find rows where something was written.', 'WHERE column IS NOT NULL', 'SELECT company_name, email FROM customers WHERE email IS NOT NULL LIMIT 10'],
  ['Filtering', 'EXISTS', 'Keep rows that have at least one matching row in another table, like customers who ordered something.', 'WHERE EXISTS (SELECT 1 FROM other WHERE ...)', 'SELECT company_name FROM customers c WHERE EXISTS (SELECT 1 FROM orders o WHERE o.customer_id = c.id) LIMIT 10'],
  ['Filtering', 'NOT EXISTS', 'Keep rows with no match in another table, like customers who never ordered.', 'WHERE NOT EXISTS (SELECT 1 FROM other WHERE ...)', 'SELECT company_name FROM customers c WHERE NOT EXISTS (SELECT 1 FROM orders o WHERE o.customer_id = c.id)'],
  // ---------- Sorting and paging
  ['Sorting and paging', 'ORDER BY (small first)', 'Put rows in order, smallest or A first. ASC is the default.', 'ORDER BY column ASC', 'SELECT name, unit_price FROM products ORDER BY unit_price ASC'],
  ['Sorting and paging', 'ORDER BY DESC (big first)', 'Put the biggest or Z first.', 'ORDER BY column DESC', 'SELECT name, unit_price FROM products ORDER BY unit_price DESC'],
  ['Sorting and paging', 'Sort by two columns', 'Sort by the first column, and when two rows tie, by the second.', 'ORDER BY column1, column2 DESC', 'SELECT country, city, company_name FROM customers ORDER BY country, city LIMIT 20'],
  ['Sorting and paging', 'LIMIT / TOP', 'Only show the first few rows. SQL Server says TOP, the others say LIMIT.', { all: 'SELECT ... LIMIT 5', mssql: 'SELECT TOP 5 ...' }, 'SELECT name, unit_price FROM products ORDER BY unit_price DESC LIMIT 5'],
  ['Sorting and paging', 'OFFSET (pages)', 'Skip some rows, then show the next ones. That is how page 2, 3, 4 work.', { all: 'LIMIT 10 OFFSET 20', mssql: 'ORDER BY col OFFSET 20 ROWS FETCH NEXT 10 ROWS ONLY' }, { all: 'SELECT id, company_name FROM customers ORDER BY id LIMIT 10 OFFSET 20', mssql: 'SELECT id, company_name FROM customers ORDER BY id OFFSET 20 ROWS FETCH NEXT 10 ROWS ONLY' }],
  ['Sorting and paging', 'Random order', 'Shuffle the rows, like picking names out of a hat.', { sqlite: 'ORDER BY RANDOM()', postgres: 'ORDER BY RANDOM()', mysql: 'ORDER BY RAND()', mssql: 'ORDER BY NEWID()' }, { sqlite: 'SELECT company_name FROM customers ORDER BY RANDOM() LIMIT 3', postgres: 'SELECT company_name FROM customers ORDER BY RANDOM() LIMIT 3', mysql: 'SELECT company_name FROM customers ORDER BY RAND() LIMIT 3', mssql: 'SELECT TOP 3 company_name FROM customers ORDER BY NEWID()' }],
  // ---------- Totals and groups
  ['Totals and groups', 'COUNT(*)', 'Count how many rows there are.', 'SELECT COUNT(*) FROM table_name', 'SELECT COUNT(*) AS how_many_orders FROM orders'],
  ['Totals and groups', 'COUNT(column)', 'Count rows where that column is not empty.', 'SELECT COUNT(column)', 'SELECT COUNT(employee_id) AS orders_with_a_salesperson FROM orders'],
  ['Totals and groups', 'COUNT(DISTINCT)', 'Count how many different values there are.', 'SELECT COUNT(DISTINCT column)', 'SELECT COUNT(DISTINCT country) AS countries FROM customers'],
  ['Totals and groups', 'SUM', 'Add all the numbers up.', 'SELECT SUM(column)', 'SELECT SUM(quantity) AS items_sold FROM order_items'],
  ['Totals and groups', 'AVG', 'The average: add up and divide by how many.', 'SELECT AVG(column)', 'SELECT AVG(unit_price) AS average_price FROM products'],
  ['Totals and groups', 'MIN and MAX', 'The smallest and the biggest value. Works on dates too (earliest and latest).', 'SELECT MIN(column), MAX(column)', 'SELECT MIN(order_date) AS first_order, MAX(order_date) AS last_order FROM orders'],
  ['Totals and groups', 'GROUP BY', 'Make piles by a value, then count or total each pile.', 'SELECT column, COUNT(*) FROM t GROUP BY column', 'SELECT status, COUNT(*) AS orders FROM orders GROUP BY status ORDER BY orders DESC'],
  ['Totals and groups', 'GROUP BY two columns', 'Piles inside piles, like each segment inside each country.', 'GROUP BY column1, column2', 'SELECT country, segment, COUNT(*) AS customers FROM customers GROUP BY country, segment ORDER BY country, customers DESC'],
  ['Totals and groups', 'HAVING', 'Filter the piles after grouping. WHERE filters rows, HAVING filters totals.', 'GROUP BY column HAVING COUNT(*) > 5', 'SELECT city, COUNT(*) AS customers FROM customers GROUP BY city HAVING COUNT(*) >= 8 ORDER BY customers DESC'],
  ['Totals and groups', 'Revenue per group', 'Total money per group: add up quantity × price.', 'SUM(quantity * price)', 'SELECT p.name, SUM(oi.quantity * oi.unit_price) AS revenue FROM order_items oi JOIN products p ON p.id = oi.product_id GROUP BY p.name ORDER BY revenue DESC LIMIT 10'],
  ['Totals and groups', 'List values in one cell', 'Glue all the values of a pile into one line of text.', { sqlite: "GROUP_CONCAT(column, ', ')", postgres: "STRING_AGG(column, ', ')", mysql: "GROUP_CONCAT(column SEPARATOR ', ')", mssql: "STRING_AGG(column, ', ')" }, { sqlite: "SELECT country, GROUP_CONCAT(DISTINCT city) AS cities FROM customers GROUP BY country", postgres: "SELECT country, STRING_AGG(DISTINCT city, ', ') AS cities FROM customers GROUP BY country", mysql: "SELECT country, GROUP_CONCAT(DISTINCT city SEPARATOR ', ') AS cities FROM customers GROUP BY country", mssql: "SELECT country, STRING_AGG(city, ', ') AS cities FROM (SELECT DISTINCT country, city FROM customers) x GROUP BY country" }],
  ['Totals and groups', 'Count only some rows', 'Count rows that match a rule, next to the full count.', "SUM(CASE WHEN rule THEN 1 ELSE 0 END)", "SELECT COUNT(*) AS all_orders, SUM(CASE WHEN status = 'delivered' THEN 1 ELSE 0 END) AS delivered FROM orders"],
  // ---------- Joining tables
  ['Joining tables', 'JOIN (INNER)', 'Put two tables side by side, matching rows by their link. Rows without a partner are left out.', 'FROM a JOIN b ON b.id = a.b_id', 'SELECT o.id, o.order_date, c.company_name FROM orders o JOIN customers c ON c.id = o.customer_id LIMIT 10'],
  ['Joining tables', 'LEFT JOIN', 'Keep every row from the first table, even when it has no partner. The missing side is empty.', 'FROM a LEFT JOIN b ON ...', 'SELECT c.company_name, o.id AS order_id FROM customers c LEFT JOIN orders o ON o.customer_id = c.id WHERE o.id IS NULL'],
  ['Joining tables', 'RIGHT JOIN', 'Like LEFT JOIN, but keeps every row from the second table.', 'FROM a RIGHT JOIN b ON ...', 'SELECT o.id, c.company_name FROM orders o RIGHT JOIN customers c ON c.id = o.customer_id LIMIT 10'],
  ['Joining tables', 'FULL OUTER JOIN', 'Keep every row from both tables, matched where possible. MySQL has no FULL JOIN, so it glues a LEFT and a RIGHT JOIN together.', 'FROM a FULL OUTER JOIN b ON ...', { all: 'SELECT d.name AS department, e.first_name FROM departments d FULL OUTER JOIN employees e ON e.department_id = d.id LIMIT 20', mysql: 'SELECT d.name AS department, e.first_name FROM departments d LEFT JOIN employees e ON e.department_id = d.id UNION SELECT d.name, e.first_name FROM departments d RIGHT JOIN employees e ON e.department_id = d.id LIMIT 20' }],
  ['Joining tables', 'Three tables', 'Chain joins one after another to walk from table to table.', 'FROM a JOIN b ON ... JOIN c ON ...', 'SELECT c.company_name, p.name AS product, oi.quantity FROM order_items oi JOIN orders o ON o.id = oi.order_id JOIN customers c ON c.id = o.customer_id JOIN products p ON p.id = oi.product_id LIMIT 10'],
  ['Joining tables', 'Self join', 'Join a table to itself, like pairing employees who work in the same department.', 'FROM t a JOIN t b ON a.x = b.x', 'SELECT a.first_name, b.first_name AS colleague, a.department_id FROM employees a JOIN employees b ON a.department_id = b.department_id AND a.id < b.id LIMIT 10'],
  ['Joining tables', 'CROSS JOIN', 'Pair every row of one table with every row of the other. Use with care: it grows fast.', 'FROM a CROSS JOIN b', 'SELECT c.name AS category, d.name AS department FROM categories c CROSS JOIN departments d LIMIT 12'],
  // ---------- Text
  ['Text', 'UPPER / LOWER', 'Change text to CAPITALS or small letters.', 'UPPER(column), LOWER(column)', 'SELECT UPPER(company_name) AS loud, LOWER(email) AS quiet FROM customers LIMIT 5'],
  ['Text', 'Length of text', 'Count the letters in a piece of text.', { all: 'LENGTH(column)', mysql: 'CHAR_LENGTH(column)', mssql: 'LEN(column)' }, { all: 'SELECT company_name, LENGTH(company_name) AS letters FROM customers ORDER BY letters DESC LIMIT 5', mysql: 'SELECT company_name, CHAR_LENGTH(company_name) AS letters FROM customers ORDER BY letters DESC LIMIT 5', mssql: 'SELECT TOP 5 company_name, LEN(company_name) AS letters FROM customers ORDER BY letters DESC' }],
  ['Text', 'TRIM', 'Remove spaces from the start and end of text. LTRIM and RTRIM do one side only.', 'TRIM(column)', "SELECT TRIM('   hello   ') AS tidy"],
  ['Text', 'Part of text (SUBSTRING)', 'Take a piece of text: start at a letter, take some letters.', { sqlite: 'SUBSTR(column, start, length)', all: 'SUBSTRING(column, start, length)' }, { sqlite: 'SELECT sku, SUBSTR(sku, 4, 4) AS number_part FROM products LIMIT 5', all: 'SELECT sku, SUBSTRING(sku, 4, 4) AS number_part FROM products LIMIT 5' }],
  ['Text', 'First / last letters', 'Take letters from the left or right end.', { sqlite: 'SUBSTR(x, 1, 3), SUBSTR(x, -3)', all: 'LEFT(x, 3), RIGHT(x, 3)' }, { sqlite: 'SELECT name, SUBSTR(name, 1, 3) AS first3, SUBSTR(name, -3) AS last3 FROM products LIMIT 5', all: 'SELECT name, LEFT(name, 3) AS first3, RIGHT(name, 3) AS last3 FROM products LIMIT 5' }],
  ['Text', 'Join text together', 'Stick pieces of text together, like first name + space + last name.', { sqlite: "a || ' ' || b", all: "CONCAT(a, ' ', b)" }, { sqlite: "SELECT first_name || ' ' || last_name AS full_name FROM employees LIMIT 5", all: "SELECT CONCAT(first_name, ' ', last_name) AS full_name FROM employees LIMIT 5" }],
  ['Text', 'REPLACE', 'Swap every copy of some text for other text.', "REPLACE(column, 'old', 'new')", "SELECT name, REPLACE(name, 'Pack', 'Box') AS renamed FROM products WHERE name LIKE '%pack%'"],
  ['Text', 'Find a letter (position)', 'Where is this text inside that text? Answers with a number, 0 if not found.', { sqlite: "INSTR(column, '@')", postgres: "POSITION('@' IN column)", mysql: "INSTR(column, '@')", mssql: "CHARINDEX('@', column)" }, { sqlite: "SELECT email, INSTR(email, '@') AS at_sign FROM customers LIMIT 5", postgres: "SELECT email, POSITION('@' IN email) AS at_sign FROM customers LIMIT 5", mysql: "SELECT email, INSTR(email, '@') AS at_sign FROM customers LIMIT 5", mssql: "SELECT TOP 5 email, CHARINDEX('@', email) AS at_sign FROM customers" }],
  ['Text', 'Email domain', 'A mix of the above: take everything after the @.', { sqlite: "SUBSTR(email, INSTR(email, '@') + 1)", postgres: "SPLIT_PART(email, '@', 2)", mysql: "SUBSTRING_INDEX(email, '@', -1)", mssql: "SUBSTRING(email, CHARINDEX('@', email) + 1, 100)" }, { sqlite: "SELECT SUBSTR(email, INSTR(email, '@') + 1) AS domain, COUNT(*) AS people FROM customers GROUP BY domain ORDER BY people DESC LIMIT 10", postgres: "SELECT SPLIT_PART(email, '@', 2) AS domain, COUNT(*) AS people FROM customers GROUP BY domain ORDER BY people DESC LIMIT 10", mysql: "SELECT SUBSTRING_INDEX(email, '@', -1) AS domain, COUNT(*) AS people FROM customers GROUP BY domain ORDER BY people DESC LIMIT 10", mssql: "SELECT TOP 10 SUBSTRING(email, CHARINDEX('@', email) + 1, 100) AS domain, COUNT(*) AS people FROM customers GROUP BY SUBSTRING(email, CHARINDEX('@', email) + 1, 100) ORDER BY people DESC" }],
  ['Text', 'Pad with zeros', 'Make numbers the same width, like 7 → 00007.', { sqlite: "SUBSTR('00000' || id, -5)", postgres: "LPAD(id::text, 5, '0')", mysql: "LPAD(id, 5, '0')", mssql: "RIGHT('00000' + CAST(id AS VARCHAR(10)), 5)" }, { sqlite: "SELECT id, SUBSTR('00000' || id, -5) AS code FROM orders LIMIT 5", postgres: "SELECT id, LPAD(id::text, 5, '0') AS code FROM orders LIMIT 5", mysql: "SELECT id, LPAD(id, 5, '0') AS code FROM orders LIMIT 5", mssql: "SELECT TOP 5 id, RIGHT('00000' + CAST(id AS VARCHAR(10)), 5) AS code FROM orders" }],
  ['Text', 'Case-insensitive search', 'Find text whatever its capitals. PostgreSQL uses ILIKE; the others ignore capitals with LIKE already.', { postgres: "column ILIKE '%word%'", all: "LOWER(column) LIKE '%word%'" }, { postgres: "SELECT company_name FROM customers WHERE company_name ILIKE '%GOLDEN%'", all: "SELECT company_name FROM customers WHERE LOWER(company_name) LIKE '%golden%'" }],
  // ---------- Numbers and maths
  ['Numbers and maths', '+ − × ÷', 'Add, subtract, multiply (*) and divide (/). Tip: whole number ÷ whole number drops the decimals in some databases, so multiply by 1.0 first.', 'column * 1.0 / other', 'SELECT name, unit_price, unit_price * 1.15 AS price_with_tax FROM products LIMIT 5'],
  ['Numbers and maths', 'ROUND', 'Round to a number of decimal places.', 'ROUND(column, 2)', 'SELECT name, ROUND(unit_price * 1.155, 2) AS rounded FROM products LIMIT 5'],
  ['Numbers and maths', 'Round up / down', 'CEIL rounds up, FLOOR rounds down to a whole number.', { sqlite: 'CAST(x AS INTEGER) rounds down', mssql: 'CEILING(x), FLOOR(x)', all: 'CEIL(x), FLOOR(x)' }, { sqlite: 'SELECT unit_price, CAST(unit_price AS INTEGER) AS rounded_down, CAST(unit_price AS INTEGER) + (unit_price > CAST(unit_price AS INTEGER)) AS rounded_up FROM products LIMIT 5', mssql: 'SELECT TOP 5 unit_price, FLOOR(unit_price) AS rounded_down, CEILING(unit_price) AS rounded_up FROM products', all: 'SELECT unit_price, FLOOR(unit_price) AS rounded_down, CEIL(unit_price) AS rounded_up FROM products LIMIT 5' }],
  ['Numbers and maths', 'ABS', 'Remove the minus sign.', 'ABS(column)', 'SELECT ABS(-42) AS without_minus'],
  ['Numbers and maths', 'Remainder (%)', 'What is left over after dividing. id % 2 = 0 means an even number.', 'column % 2', 'SELECT id, id % 2 AS odd_or_even FROM orders LIMIT 6'],
  ['Numbers and maths', 'Percentage of the total', 'How big is each group compared to everything?', 'COUNT(*) * 100.0 / (SELECT COUNT(*) FROM t)', 'SELECT status, ROUND(COUNT(*) * 100.0 / (SELECT COUNT(*) FROM orders), 1) AS percent FROM orders GROUP BY status ORDER BY percent DESC'],
  ['Numbers and maths', 'Price bands', 'Put numbers into buckets of equal size by dividing and rounding down.', 'CAST(x / 10 AS INTEGER) * 10', { all: 'SELECT CAST(unit_price / 10 AS INTEGER) * 10 AS band_from, COUNT(*) AS products FROM products GROUP BY CAST(unit_price / 10 AS INTEGER) * 10 ORDER BY band_from', postgres: 'SELECT FLOOR(unit_price / 10) * 10 AS band_from, COUNT(*) AS products FROM products GROUP BY 1 ORDER BY 1', mysql: 'SELECT FLOOR(unit_price / 10) * 10 AS band_from, COUNT(*) AS products FROM products GROUP BY band_from ORDER BY band_from' }],
  // ---------- Dates and times
  ['Dates and times', "Today's date", "Get today's date from the database's clock.", { sqlite: "DATE('now')", postgres: 'CURRENT_DATE', mysql: 'CURDATE()', mssql: 'CAST(GETDATE() AS DATE)' }, { sqlite: "SELECT DATE('now') AS today", postgres: 'SELECT CURRENT_DATE AS today', mysql: 'SELECT CURDATE() AS today', mssql: 'SELECT CAST(GETDATE() AS DATE) AS today' }],
  ['Dates and times', 'Now (date and time)', 'The date and the time right now.', { sqlite: "DATETIME('now')", postgres: 'NOW()', mysql: 'NOW()', mssql: 'GETDATE()' }, { sqlite: "SELECT DATETIME('now') AS right_now", postgres: 'SELECT NOW() AS right_now', mysql: 'SELECT NOW() AS right_now', mssql: 'SELECT GETDATE() AS right_now' }],
  ['Dates and times', 'Year of a date', 'Pull out just the year.', { sqlite: "STRFTIME('%Y', date)", postgres: 'EXTRACT(YEAR FROM date)', all: 'YEAR(date)' }, { sqlite: "SELECT STRFTIME('%Y', order_date) AS year, COUNT(*) AS orders FROM orders GROUP BY year", postgres: 'SELECT EXTRACT(YEAR FROM order_date) AS year, COUNT(*) AS orders FROM orders GROUP BY 1 ORDER BY 1', all: 'SELECT YEAR(order_date) AS year, COUNT(*) AS orders FROM orders GROUP BY YEAR(order_date) ORDER BY year' }],
  ['Dates and times', 'Month of a date', 'Pull out the month number (1 to 12).', { sqlite: "STRFTIME('%m', date)", postgres: 'EXTRACT(MONTH FROM date)', all: 'MONTH(date)' }, { sqlite: "SELECT STRFTIME('%m', order_date) AS month, COUNT(*) AS orders FROM orders GROUP BY month ORDER BY month", postgres: 'SELECT EXTRACT(MONTH FROM order_date) AS month, COUNT(*) AS orders FROM orders GROUP BY 1 ORDER BY 1', all: 'SELECT MONTH(order_date) AS month, COUNT(*) AS orders FROM orders GROUP BY MONTH(order_date) ORDER BY month' }],
  ['Dates and times', 'Totals per month', 'Turn a date into "2026-07" so you can group by month.', { sqlite: "STRFTIME('%Y-%m', date)", postgres: "TO_CHAR(date, 'YYYY-MM')", mysql: "DATE_FORMAT(date, '%Y-%m')", mssql: "FORMAT(date, 'yyyy-MM')" }, { sqlite: "SELECT STRFTIME('%Y-%m', order_date) AS month, COUNT(*) AS orders FROM orders GROUP BY month ORDER BY month", postgres: "SELECT TO_CHAR(order_date, 'YYYY-MM') AS month, COUNT(*) AS orders FROM orders GROUP BY 1 ORDER BY 1", mysql: "SELECT DATE_FORMAT(order_date, '%Y-%m') AS month, COUNT(*) AS orders FROM orders GROUP BY month ORDER BY month", mssql: "SELECT FORMAT(order_date, 'yyyy-MM') AS month, COUNT(*) AS orders FROM orders GROUP BY FORMAT(order_date, 'yyyy-MM') ORDER BY month" }],
  ['Dates and times', 'Day of the week', 'Which weekday a date falls on.', { sqlite: "STRFTIME('%w', date) (0 = Sunday)", postgres: "TO_CHAR(date, 'Day')", mysql: 'DAYNAME(date)', mssql: 'DATENAME(weekday, date)' }, { sqlite: "SELECT STRFTIME('%w', order_date) AS weekday_number, COUNT(*) AS orders FROM orders GROUP BY weekday_number ORDER BY weekday_number", postgres: "SELECT TO_CHAR(order_date, 'Day') AS weekday, COUNT(*) AS orders FROM orders GROUP BY 1", mysql: 'SELECT DAYNAME(order_date) AS weekday, COUNT(*) AS orders FROM orders GROUP BY weekday', mssql: 'SELECT DATENAME(weekday, order_date) AS weekday, COUNT(*) AS orders FROM orders GROUP BY DATENAME(weekday, order_date)' }],
  ['Dates and times', 'Add days to a date', 'Move a date forward or back, like "30 days after the order".', { sqlite: "DATE(date, '+30 days')", postgres: "date + INTERVAL '30 days'", mysql: 'DATE_ADD(date, INTERVAL 30 DAY)', mssql: 'DATEADD(day, 30, date)' }, { sqlite: "SELECT order_date, DATE(order_date, '+30 days') AS pay_by FROM orders LIMIT 5", postgres: "SELECT order_date, order_date + INTERVAL '30 days' AS pay_by FROM orders LIMIT 5", mysql: 'SELECT order_date, DATE_ADD(order_date, INTERVAL 30 DAY) AS pay_by FROM orders LIMIT 5', mssql: 'SELECT TOP 5 order_date, DATEADD(day, 30, order_date) AS pay_by FROM orders' }],
  ['Dates and times', 'Days between dates', 'How many days from one date to another.', { sqlite: 'JULIANDAY(later) - JULIANDAY(earlier)', postgres: 'later - earlier', mysql: 'DATEDIFF(later, earlier)', mssql: 'DATEDIFF(day, earlier, later)' }, { sqlite: "SELECT id, order_date, CAST(JULIANDAY('now') - JULIANDAY(order_date) AS INTEGER) AS days_ago FROM orders ORDER BY order_date DESC LIMIT 5", postgres: 'SELECT id, order_date, CURRENT_DATE - order_date AS days_ago FROM orders ORDER BY order_date DESC LIMIT 5', mysql: 'SELECT id, order_date, DATEDIFF(CURDATE(), order_date) AS days_ago FROM orders ORDER BY order_date DESC LIMIT 5', mssql: 'SELECT TOP 5 id, order_date, DATEDIFF(day, order_date, GETDATE()) AS days_ago FROM orders ORDER BY order_date DESC' }],
  ['Dates and times', 'Last 30 days', 'Keep only rows from the last 30 days.', { sqlite: "WHERE date >= DATE('now', '-30 days')", postgres: "WHERE date >= CURRENT_DATE - 30", mysql: 'WHERE date >= DATE_SUB(CURDATE(), INTERVAL 30 DAY)', mssql: 'WHERE date >= DATEADD(day, -30, GETDATE())' }, { sqlite: "SELECT * FROM orders WHERE order_date >= DATE('now', '-30 days') ORDER BY order_date DESC", postgres: 'SELECT * FROM orders WHERE order_date >= CURRENT_DATE - 30 ORDER BY order_date DESC', mysql: 'SELECT * FROM orders WHERE order_date >= DATE_SUB(CURDATE(), INTERVAL 30 DAY) ORDER BY order_date DESC', mssql: 'SELECT * FROM orders WHERE order_date >= DATEADD(day, -30, GETDATE()) ORDER BY order_date DESC' }],
  ['Dates and times', 'This year', 'Keep only rows from this calendar year.', { sqlite: "WHERE STRFTIME('%Y', date) = STRFTIME('%Y', 'now')", postgres: 'WHERE EXTRACT(YEAR FROM date) = EXTRACT(YEAR FROM CURRENT_DATE)', all: 'WHERE YEAR(date) = YEAR(GETDATE())', mysql: 'WHERE YEAR(date) = YEAR(CURDATE())' }, { sqlite: "SELECT COUNT(*) AS orders_this_year FROM orders WHERE STRFTIME('%Y', order_date) = STRFTIME('%Y', 'now')", postgres: 'SELECT COUNT(*) AS orders_this_year FROM orders WHERE EXTRACT(YEAR FROM order_date) = EXTRACT(YEAR FROM CURRENT_DATE)', mysql: 'SELECT COUNT(*) AS orders_this_year FROM orders WHERE YEAR(order_date) = YEAR(CURDATE())', mssql: 'SELECT COUNT(*) AS orders_this_year FROM orders WHERE YEAR(order_date) = YEAR(GETDATE())' }],
  ['Dates and times', 'Format a date', 'Show a date the way you like, such as 24/09/2026.', { sqlite: "STRFTIME('%d/%m/%Y', date)", postgres: "TO_CHAR(date, 'DD/MM/YYYY')", mysql: "DATE_FORMAT(date, '%d/%m/%Y')", mssql: "FORMAT(date, 'dd/MM/yyyy')" }, { sqlite: "SELECT order_date, STRFTIME('%d/%m/%Y', order_date) AS nice_date FROM orders LIMIT 5", postgres: "SELECT order_date, TO_CHAR(order_date, 'DD/MM/YYYY') AS nice_date FROM orders LIMIT 5", mysql: "SELECT order_date, DATE_FORMAT(order_date, '%d/%m/%Y') AS nice_date FROM orders LIMIT 5", mssql: "SELECT TOP 5 order_date, FORMAT(order_date, 'dd/MM/yyyy') AS nice_date FROM orders" }],
  ['Dates and times', 'Years between (age)', 'Whole years between a date and today, like how long someone has worked here.', { sqlite: "CAST((JULIANDAY('now') - JULIANDAY(date)) / 365.25 AS INTEGER)", postgres: 'DATE_PART(\'year\', AGE(date))', mysql: 'TIMESTAMPDIFF(YEAR, date, CURDATE())', mssql: 'DATEDIFF(year, date, GETDATE())' }, { sqlite: "SELECT first_name, hire_date, CAST((JULIANDAY('now') - JULIANDAY(hire_date)) / 365.25 AS INTEGER) AS years_here FROM employees ORDER BY years_here DESC LIMIT 5", postgres: "SELECT first_name, hire_date, DATE_PART('year', AGE(hire_date)) AS years_here FROM employees ORDER BY years_here DESC LIMIT 5", mysql: 'SELECT first_name, hire_date, TIMESTAMPDIFF(YEAR, hire_date, CURDATE()) AS years_here FROM employees ORDER BY years_here DESC LIMIT 5', mssql: 'SELECT TOP 5 first_name, hire_date, DATEDIFF(year, hire_date, GETDATE()) AS years_here FROM employees ORDER BY years_here DESC' }],
  // ---------- Conditions
  ['Conditions', 'CASE WHEN', 'Choose a value with rules, like sorting sweets into "cheap", "medium" and "dear".', "CASE WHEN rule THEN 'a' WHEN rule THEN 'b' ELSE 'c' END", "SELECT name, unit_price, CASE WHEN unit_price < 8 THEN 'cheap' WHEN unit_price < 20 THEN 'medium' ELSE 'dear' END AS price_band FROM products"],
  ['Conditions', 'CASE (simple)', 'Swap codes for words.', "CASE column WHEN 'x' THEN 'X words' ... END", "SELECT id, CASE status WHEN 'delivered' THEN 'Arrived' WHEN 'shipped' THEN 'On the way' WHEN 'pending' THEN 'Not sent yet' ELSE 'Stopped' END AS what_happened FROM orders LIMIT 10"],
  ['Conditions', 'COALESCE', 'Use the first value that is not empty. Great for "show 0 instead of empty".', "COALESCE(column, 'fallback')", "SELECT id, COALESCE(employee_id, 0) AS salesperson FROM orders LIMIT 5"],
  ['Conditions', 'NULLIF', 'Turn a value into empty. Mostly used to avoid dividing by zero.', 'x / NULLIF(y, 0)', 'SELECT name, units_in_stock, ROUND(unit_price / NULLIF(units_in_stock, 0), 4) AS price_per_unit_in_stock FROM products LIMIT 5'],
  ['Conditions', 'IF in one line', 'A short CASE: if the rule is true give one value, otherwise another.', { sqlite: "IIF(rule, 'yes', 'no')", mysql: "IF(rule, 'yes', 'no')", mssql: "IIF(rule, 'yes', 'no')", postgres: "CASE WHEN rule THEN 'yes' ELSE 'no' END" }, { sqlite: "SELECT name, IIF(units_in_stock < 50, 'reorder', 'fine') AS stock FROM products", mysql: "SELECT name, IF(units_in_stock < 50, 'reorder', 'fine') AS stock FROM products", mssql: "SELECT name, IIF(units_in_stock < 50, 'reorder', 'fine') AS stock FROM products", postgres: "SELECT name, CASE WHEN units_in_stock < 50 THEN 'reorder' ELSE 'fine' END AS stock FROM products" }],
  ['Conditions', 'Bigger / smaller of two', 'Pick the larger (or smaller) of several values on the same row.', { sqlite: 'MAX(a, b), MIN(a, b)', all: 'GREATEST(a, b), LEAST(a, b)', mssql: 'CASE WHEN a > b THEN a ELSE b END' }, { sqlite: 'SELECT quantity, MAX(quantity, 10) AS at_least_ten FROM order_items LIMIT 5', all: 'SELECT quantity, GREATEST(quantity, 10) AS at_least_ten FROM order_items LIMIT 5', mssql: 'SELECT TOP 5 quantity, CASE WHEN quantity > 10 THEN quantity ELSE 10 END AS at_least_ten FROM order_items' }],
  // ---------- Combining results
  ['Combining results', 'UNION', 'Stack two answers on top of each other and remove repeats. Both must have the same number of columns.', 'SELECT ... UNION SELECT ...', 'SELECT city FROM customers UNION SELECT ship_city FROM orders ORDER BY city'],
  ['Combining results', 'UNION ALL', 'Stack two answers and keep repeats. Faster than UNION.', 'SELECT ... UNION ALL SELECT ...', "SELECT 'customer' AS who, contact_name AS name FROM customers UNION ALL SELECT 'employee', first_name FROM employees LIMIT 20"],
  ['Combining results', 'INTERSECT', 'Only values that appear in both answers.', 'SELECT ... INTERSECT SELECT ...', 'SELECT city FROM customers INTERSECT SELECT ship_city FROM orders'],
  ['Combining results', 'EXCEPT', 'Values in the first answer that are not in the second.', 'SELECT ... EXCEPT SELECT ...', 'SELECT id FROM customers EXCEPT SELECT customer_id FROM orders'],
  // ---------- Subqueries and WITH
  ['Subqueries and WITH', 'Subquery in WHERE', 'Use one question inside another, like "products priced above the average price".', 'WHERE column > (SELECT AVG(column) FROM t)', 'SELECT name, unit_price FROM products WHERE unit_price > (SELECT AVG(unit_price) FROM products) ORDER BY unit_price DESC'],
  ['Subqueries and WITH', 'Subquery as a column', 'Work something out for every row with a small question of its own.', 'SELECT a, (SELECT COUNT(*) FROM b WHERE b.a_id = a.id)', 'SELECT company_name, (SELECT COUNT(*) FROM orders o WHERE o.customer_id = c.id) AS orders FROM customers c ORDER BY orders DESC LIMIT 10'],
  ['Subqueries and WITH', 'Subquery in FROM', 'Treat an answer like a temporary table and ask about it.', 'SELECT ... FROM (SELECT ...) AS x', 'SELECT AVG(order_count) AS average_orders_per_customer FROM (SELECT customer_id, COUNT(*) AS order_count FROM orders GROUP BY customer_id) AS x'],
  ['Subqueries and WITH', 'WITH (named step)', 'Give a step a name first, then use it. Makes long questions easy to read.', 'WITH step AS (SELECT ...) SELECT ... FROM step', "WITH revenue AS (SELECT o.customer_id, SUM(oi.quantity * oi.unit_price) AS total FROM orders o JOIN order_items oi ON oi.order_id = o.id GROUP BY o.customer_id) SELECT c.company_name, r.total FROM revenue r JOIN customers c ON c.id = r.customer_id ORDER BY r.total DESC LIMIT 10"],
  ['Subqueries and WITH', 'WITH RECURSIVE (counting)', 'A step that uses itself, like counting 1, 2, 3… SQL Server leaves out the word RECURSIVE.', { all: 'WITH RECURSIVE n(x) AS (SELECT 1 UNION ALL SELECT x + 1 FROM n WHERE x < 10) SELECT x FROM n', mssql: 'WITH n(x) AS (SELECT 1 UNION ALL SELECT x + 1 FROM n WHERE x < 10) SELECT x FROM n' }, { all: 'WITH RECURSIVE n(x) AS (SELECT 1 UNION ALL SELECT x + 1 FROM n WHERE x < 10) SELECT x FROM n', mssql: 'WITH n(x) AS (SELECT 1 UNION ALL SELECT x + 1 FROM n WHERE x < 10) SELECT x FROM n' }],
  // ---------- Window functions
  ['Window functions', 'ROW_NUMBER', 'Number the rows 1, 2, 3 in the order you choose.', 'ROW_NUMBER() OVER (ORDER BY column)', 'SELECT ROW_NUMBER() OVER (ORDER BY unit_price DESC) AS position, name, unit_price FROM products LIMIT 10'],
  ['Window functions', 'RANK and DENSE_RANK', 'Positions like a race. Ties share a place. RANK skips the next place after a tie, DENSE_RANK does not.', 'RANK() OVER (ORDER BY column DESC)', 'SELECT name, units_in_stock, RANK() OVER (ORDER BY units_in_stock DESC) AS rank, DENSE_RANK() OVER (ORDER BY units_in_stock DESC) AS dense_rank FROM products LIMIT 10'],
  ['Window functions', 'Number within each group', 'Start counting again for every group, with PARTITION BY.', 'ROW_NUMBER() OVER (PARTITION BY group ORDER BY column)', 'SELECT category_id, name, unit_price, ROW_NUMBER() OVER (PARTITION BY category_id ORDER BY unit_price DESC) AS place_in_category FROM products'],
  ['Window functions', 'Top 3 in each group', 'Number inside each group, then keep the first few.', 'WITH x AS (... ROW_NUMBER() OVER (PARTITION BY ...) AS n) SELECT ... WHERE n <= 3', 'WITH ranked AS (SELECT category_id, name, unit_price, ROW_NUMBER() OVER (PARTITION BY category_id ORDER BY unit_price DESC) AS n FROM products) SELECT * FROM ranked WHERE n <= 3'],
  ['Window functions', 'Running total', 'Keep adding as you go down the rows, like a savings balance.', 'SUM(column) OVER (ORDER BY date)', { all: "WITH m AS (SELECT STRFTIME('%Y-%m', order_date) AS month, COUNT(*) AS orders FROM orders GROUP BY month) SELECT month, orders, SUM(orders) OVER (ORDER BY month) AS running_total FROM m", postgres: "WITH m AS (SELECT TO_CHAR(order_date, 'YYYY-MM') AS month, COUNT(*) AS orders FROM orders GROUP BY 1) SELECT month, orders, SUM(orders) OVER (ORDER BY month) AS running_total FROM m", mysql: "WITH m AS (SELECT DATE_FORMAT(order_date, '%Y-%m') AS month, COUNT(*) AS orders FROM orders GROUP BY month) SELECT month, orders, SUM(orders) OVER (ORDER BY month) AS running_total FROM m", mssql: "WITH m AS (SELECT FORMAT(order_date, 'yyyy-MM') AS month, COUNT(*) AS orders FROM orders GROUP BY FORMAT(order_date, 'yyyy-MM')) SELECT month, orders, SUM(orders) OVER (ORDER BY month) AS running_total FROM m" }],
  ['Window functions', 'Group total on every row', 'Show the total of the group next to each row, without squashing the rows.', 'SUM(column) OVER (PARTITION BY group)', 'SELECT name, category_id, units_in_stock, SUM(units_in_stock) OVER (PARTITION BY category_id) AS category_stock FROM products'],
  ['Window functions', 'Share of the total', "Each row's slice of the whole pie, in percent.", '100.0 * x / SUM(x) OVER ()', 'SELECT name, units_in_stock, ROUND(100.0 * units_in_stock / SUM(units_in_stock) OVER (), 1) AS percent_of_stock FROM products ORDER BY percent_of_stock DESC LIMIT 10'],
  ['Window functions', 'LAG and LEAD', 'Peek at the row before (LAG) or after (LEAD). Handy for "change since last month".', 'LAG(column) OVER (ORDER BY date)', { all: "WITH m AS (SELECT STRFTIME('%Y-%m', order_date) AS month, COUNT(*) AS orders FROM orders GROUP BY month) SELECT month, orders, LAG(orders) OVER (ORDER BY month) AS last_month, orders - LAG(orders) OVER (ORDER BY month) AS difference FROM m", postgres: "WITH m AS (SELECT TO_CHAR(order_date, 'YYYY-MM') AS month, COUNT(*) AS orders FROM orders GROUP BY 1) SELECT month, orders, LAG(orders) OVER (ORDER BY month) AS last_month, orders - LAG(orders) OVER (ORDER BY month) AS difference FROM m", mysql: "WITH m AS (SELECT DATE_FORMAT(order_date, '%Y-%m') AS month, COUNT(*) AS orders FROM orders GROUP BY month) SELECT month, orders, LAG(orders) OVER (ORDER BY month) AS last_month, orders - LAG(orders) OVER (ORDER BY month) AS difference FROM m", mssql: "WITH m AS (SELECT FORMAT(order_date, 'yyyy-MM') AS month, COUNT(*) AS orders FROM orders GROUP BY FORMAT(order_date, 'yyyy-MM')) SELECT month, orders, LAG(orders) OVER (ORDER BY month) AS last_month, orders - LAG(orders) OVER (ORDER BY month) AS difference FROM m" }],
  ['Window functions', 'Moving average', 'The average of this row and the two before it. Smooths out bumps.', 'AVG(x) OVER (ORDER BY d ROWS BETWEEN 2 PRECEDING AND CURRENT ROW)', { all: "WITH m AS (SELECT STRFTIME('%Y-%m', order_date) AS month, COUNT(*) AS orders FROM orders GROUP BY month) SELECT month, orders, ROUND(AVG(orders) OVER (ORDER BY month ROWS BETWEEN 2 PRECEDING AND CURRENT ROW), 1) AS three_month_average FROM m", postgres: "WITH m AS (SELECT TO_CHAR(order_date, 'YYYY-MM') AS month, COUNT(*) AS orders FROM orders GROUP BY 1) SELECT month, orders, ROUND(AVG(orders) OVER (ORDER BY month ROWS BETWEEN 2 PRECEDING AND CURRENT ROW), 1) AS three_month_average FROM m", mysql: "WITH m AS (SELECT DATE_FORMAT(order_date, '%Y-%m') AS month, COUNT(*) AS orders FROM orders GROUP BY month) SELECT month, orders, ROUND(AVG(orders) OVER (ORDER BY month ROWS BETWEEN 2 PRECEDING AND CURRENT ROW), 1) AS three_month_average FROM m", mssql: "WITH m AS (SELECT FORMAT(order_date, 'yyyy-MM') AS month, COUNT(*) AS orders FROM orders GROUP BY FORMAT(order_date, 'yyyy-MM')) SELECT month, orders, ROUND(AVG(orders * 1.0) OVER (ORDER BY month ROWS BETWEEN 2 PRECEDING AND CURRENT ROW), 1) AS three_month_average FROM m" }],
  ['Window functions', 'FIRST_VALUE', 'Show the first value of the group on every row, like the cheapest product in each category.', 'FIRST_VALUE(x) OVER (PARTITION BY g ORDER BY y)', 'SELECT category_id, name, unit_price, FIRST_VALUE(name) OVER (PARTITION BY category_id ORDER BY unit_price) AS cheapest_in_category FROM products'],
  ['Window functions', 'NTILE (split into groups)', 'Split rows into equal groups, like top quarter, second quarter and so on.', 'NTILE(4) OVER (ORDER BY column DESC)', 'SELECT name, unit_price, NTILE(4) OVER (ORDER BY unit_price DESC) AS price_quarter FROM products'],
  // ---------- Changing data
  ['Changing data', 'INSERT one row', 'Add a new row. List the columns, then the values in the same order.', "INSERT INTO t (a, b) VALUES ('x', 'y')", "INSERT INTO categories (name, description) VALUES ('Stationery', 'Envelopes, folders and labels')"],
  ['Changing data', 'INSERT several rows', 'Add many rows at once, one bracket per row.', "INSERT INTO t (a, b) VALUES ('x', 1), ('y', 2)", "INSERT INTO departments (name, budget, floor) VALUES ('Research', 95000, 4), ('Training', 60000, 2)"],
  ['Changing data', 'INSERT from a question', 'Copy rows from one answer into a table.', 'INSERT INTO t (a, b) SELECT a, b FROM other WHERE ...', { all: "INSERT INTO categories (name, description) SELECT 'Archive ' || name, description FROM categories WHERE id = 1", mysql: "INSERT INTO categories (name, description) SELECT CONCAT('Archive ', name), description FROM categories WHERE id = 1", mssql: "INSERT INTO categories (name, description) SELECT 'Archive ' + name, description FROM categories WHERE id = 1" }],
  ['Changing data', 'UPDATE', 'Change values in rows that match. Always add WHERE, or every row changes.', "UPDATE t SET column = 'new' WHERE id = 1", "UPDATE customers SET segment = 'Wholesale' WHERE id = 1"],
  ['Changing data', 'UPDATE with maths', 'Change values using the old value, like raising prices by 5%.', 'UPDATE t SET price = price * 1.05 WHERE ...', 'UPDATE products SET unit_price = ROUND(unit_price * 1.05, 2) WHERE category_id = 1'],
  ['Changing data', 'DELETE', 'Remove rows that match. Always add WHERE, or every row goes.', 'DELETE FROM t WHERE id = 1', "DELETE FROM orders WHERE status = 'cancelled' AND order_date < '2025-03-01'"],
  ['Changing data', 'Insert or update (upsert)', 'Add the row, or change it if one with the same key already exists.', { sqlite: 'INSERT ... ON CONFLICT (key) DO UPDATE SET ...', postgres: 'INSERT ... ON CONFLICT (key) DO UPDATE SET ...', mysql: 'INSERT ... ON DUPLICATE KEY UPDATE ...', mssql: 'MERGE INTO t USING ... WHEN MATCHED THEN UPDATE ... WHEN NOT MATCHED THEN INSERT ...' }, { sqlite: "INSERT INTO products (sku, name, category_id, unit_price, units_in_stock) VALUES ('NW-1000', 'Ghana Arabica Coffee 1kg', 1, 19.5, 100) ON CONFLICT (sku) DO UPDATE SET unit_price = excluded.unit_price", postgres: "INSERT INTO products (sku, name, category_id, unit_price, units_in_stock) VALUES ('NW-1000', 'Ghana Arabica Coffee 1kg', 1, 19.5, 100) ON CONFLICT (sku) DO UPDATE SET unit_price = EXCLUDED.unit_price", mysql: "INSERT INTO products (sku, name, category_id, unit_price, units_in_stock) VALUES ('NW-1000', 'Ghana Arabica Coffee 1kg', 1, 19.5, 100) ON DUPLICATE KEY UPDATE unit_price = VALUES(unit_price)", mssql: "MERGE INTO products AS t USING (SELECT 'NW-1000' AS sku, 19.5 AS unit_price) AS s ON t.sku = s.sku WHEN MATCHED THEN UPDATE SET unit_price = s.unit_price WHEN NOT MATCHED THEN INSERT (sku, name, category_id, unit_price, units_in_stock) VALUES (s.sku, 'New product', 1, s.unit_price, 0);" }],
  ['Changing data', 'Empty a table', 'Remove every row but keep the table.', { sqlite: 'DELETE FROM t', all: 'TRUNCATE TABLE t' }, { sqlite: 'DELETE FROM table_name', all: 'TRUNCATE TABLE table_name' }],
  // ---------- Table design
  ['Table design', 'CREATE TABLE', 'Make a new table and say what goes in each column.', 'CREATE TABLE t (id ..., name TEXT NOT NULL)', { sqlite: 'CREATE TABLE suppliers (\n  id INTEGER PRIMARY KEY AUTOINCREMENT,\n  name TEXT NOT NULL,\n  country TEXT,\n  rating INTEGER\n)', postgres: 'CREATE TABLE suppliers (\n  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,\n  name VARCHAR(255) NOT NULL,\n  country VARCHAR(100),\n  rating INTEGER\n)', mysql: 'CREATE TABLE suppliers (\n  id INT AUTO_INCREMENT PRIMARY KEY,\n  name VARCHAR(255) NOT NULL,\n  country VARCHAR(100),\n  rating INT\n)', mssql: 'CREATE TABLE suppliers (\n  id INT IDENTITY(1,1) PRIMARY KEY,\n  name NVARCHAR(255) NOT NULL,\n  country NVARCHAR(100),\n  rating INT\n)' }],
  ['Table design', 'Table from a question', 'Save an answer as a brand-new table.', { all: 'CREATE TABLE new AS SELECT ...', mssql: 'SELECT ... INTO new FROM ...' }, { all: "CREATE TABLE ghana_customers AS SELECT * FROM customers WHERE country = 'Ghana'", mssql: "SELECT * INTO ghana_customers FROM customers WHERE country = 'Ghana'" }],
  ['Table design', 'Links and rules', 'PRIMARY KEY = name tag. FOREIGN KEY = link to another table. NOT NULL = required. UNIQUE = no repeats. CHECK = your own rule.', 'FOREIGN KEY (col) REFERENCES other(id)', { all: 'CREATE TABLE reviews (\n  id INTEGER PRIMARY KEY,\n  product_id INTEGER NOT NULL REFERENCES products(id),\n  stars INTEGER CHECK (stars BETWEEN 1 AND 5),\n  email TEXT UNIQUE\n)', mysql: 'CREATE TABLE reviews (\n  id INT AUTO_INCREMENT PRIMARY KEY,\n  product_id INT NOT NULL,\n  stars INT CHECK (stars BETWEEN 1 AND 5),\n  email VARCHAR(255) UNIQUE,\n  FOREIGN KEY (product_id) REFERENCES products(id)\n)' }],
  ['Table design', 'DEFAULT', 'A value used when you leave the column empty.', "column TEXT DEFAULT 'new'", { all: "ALTER TABLE customers ADD COLUMN vip INTEGER DEFAULT 0", mssql: 'ALTER TABLE customers ADD vip INT DEFAULT 0' }],
  ['Table design', 'Add a column', 'Add a new column to every row of a table.', { all: 'ALTER TABLE t ADD COLUMN name TYPE', mssql: 'ALTER TABLE t ADD name TYPE' }, { all: 'ALTER TABLE customers ADD COLUMN notes TEXT', mssql: 'ALTER TABLE customers ADD notes NVARCHAR(MAX)' }],
  ['Table design', 'Rename a column', 'Give a column a new name.', { all: 'ALTER TABLE t RENAME COLUMN old TO new', mssql: "EXEC sp_rename 't.old', 'new', 'COLUMN'" }, { all: 'ALTER TABLE customers RENAME COLUMN segment TO customer_type', mssql: "EXEC sp_rename 'customers.segment', 'customer_type', 'COLUMN'" }],
  ['Table design', 'Remove a column', 'Delete a column and everything written in it.', 'ALTER TABLE t DROP COLUMN name', 'ALTER TABLE customers DROP COLUMN phone'],
  ['Table design', 'Rename a table', 'Give a table a new name.', { all: 'ALTER TABLE old RENAME TO new', mysql: 'RENAME TABLE old TO new', mssql: "EXEC sp_rename 'old', 'new'" }, { all: 'ALTER TABLE categories RENAME TO product_groups', mysql: 'RENAME TABLE categories TO product_groups', mssql: "EXEC sp_rename 'categories', 'product_groups'" }],
  ['Table design', 'DROP TABLE', 'Delete a whole table and all its rows. IF EXISTS stops an error if it is not there.', 'DROP TABLE IF EXISTS t', 'DROP TABLE IF EXISTS ghana_customers'],
  ['Table design', 'CREATE INDEX', 'Make searching and sorting one column much faster, like the index at the back of a book.', 'CREATE INDEX name ON t (column)', 'CREATE INDEX idx_orders_date ON orders (order_date)'],
  ['Table design', 'UNIQUE INDEX', 'Make searching faster a column and also stop repeats in it.', 'CREATE UNIQUE INDEX name ON t (column)', 'CREATE UNIQUE INDEX idx_products_name ON products (name)'],
  ['Table design', 'DROP INDEX', 'Remove an index. The data is not touched.', { all: 'DROP INDEX IF EXISTS name', mysql: 'DROP INDEX name ON t', mssql: 'DROP INDEX IF EXISTS name ON t' }, { all: 'DROP INDEX IF EXISTS idx_orders_date', mysql: 'DROP INDEX IF EXISTS idx_orders_date ON orders', mssql: 'DROP INDEX IF EXISTS idx_orders_date ON orders' }],
  ['Table design', 'CREATE VIEW', 'Save a question so it behaves like a table and always shows fresh data.', 'CREATE VIEW name AS SELECT ...', 'CREATE VIEW order_totals AS SELECT order_id, SUM(quantity * unit_price) AS total FROM order_items GROUP BY order_id'],
  ['Table design', 'DROP VIEW', 'Delete a saved view. The real data is not touched.', 'DROP VIEW IF EXISTS name', 'DROP VIEW IF EXISTS order_totals'],
  // ---------- Transactions
  ['Transactions', 'BEGIN … COMMIT', 'Do several changes as one package: all of them happen, or none do.', { all: 'BEGIN; ... ; COMMIT;', mysql: 'START TRANSACTION; ... ; COMMIT;', mssql: 'BEGIN TRANSACTION; ... ; COMMIT;' }, { all: "BEGIN;\nUPDATE products SET units_in_stock = units_in_stock - 5 WHERE id = 1;\nINSERT INTO orders (customer_id, order_date, status) VALUES (1, '2026-09-24', 'pending');\nCOMMIT;", mysql: "START TRANSACTION;\nUPDATE products SET units_in_stock = units_in_stock - 5 WHERE id = 1;\nINSERT INTO orders (customer_id, order_date, status) VALUES (1, '2026-09-24', 'pending');\nCOMMIT;", mssql: "BEGIN TRANSACTION;\nUPDATE products SET units_in_stock = units_in_stock - 5 WHERE id = 1;\nINSERT INTO orders (customer_id, order_date, status) VALUES (1, '2026-09-24', 'pending');\nCOMMIT;" }],
  ['Transactions', 'ROLLBACK', 'Cancel the package: undo every change since BEGIN.', 'ROLLBACK', { all: "BEGIN;\nDELETE FROM order_items;\nROLLBACK;", mysql: "START TRANSACTION;\nDELETE FROM order_items;\nROLLBACK;", mssql: "BEGIN TRANSACTION;\nDELETE FROM order_items;\nROLLBACK;" }],
  // ---------- Types and info
  ['Types and info', 'CAST (change type)', 'Treat a value as a different kind, like text → number.', 'CAST(column AS INTEGER)', { all: "SELECT CAST('42' AS INTEGER) + 1 AS answer", mysql: "SELECT CAST('42' AS SIGNED) + 1 AS answer" }],
  ['Types and info', 'What kind is it?', 'Ask the database what kind of value something is.', { sqlite: 'TYPEOF(x)', postgres: 'pg_typeof(x)', mysql: 'look in information_schema.columns', mssql: "SQL_VARIANT_PROPERTY(x, 'BaseType')" }, { sqlite: 'SELECT unit_price, TYPEOF(unit_price) AS kind FROM products LIMIT 3', postgres: 'SELECT unit_price, pg_typeof(unit_price) AS kind FROM products LIMIT 3', mysql: "SELECT column_name, data_type FROM information_schema.columns WHERE table_name = 'products'", mssql: "SELECT TOP 3 unit_price, SQL_VARIANT_PROPERTY(unit_price, 'BaseType') AS kind FROM products" }],
  ['Types and info', 'List all tables', 'Ask the database which tables it has.', { sqlite: "SELECT name FROM sqlite_master WHERE type = 'table'", postgres: "SELECT table_name FROM information_schema.tables WHERE table_schema = 'public'", mysql: 'SHOW TABLES', mssql: 'SELECT name FROM sys.tables' }, { sqlite: "SELECT name FROM sqlite_master WHERE type = 'table' ORDER BY name", postgres: "SELECT table_name FROM information_schema.tables WHERE table_schema = 'public' ORDER BY 1", mysql: 'SHOW TABLES', mssql: 'SELECT name FROM sys.tables ORDER BY name' }],
  ['Types and info', 'Columns of a table', 'Ask which columns a table has and what kind each is.', { sqlite: 'PRAGMA table_info(t)', all: "SELECT column_name, data_type FROM information_schema.columns WHERE table_name = 't'" }, { sqlite: 'PRAGMA table_info(customers)', all: "SELECT column_name, data_type, is_nullable FROM information_schema.columns WHERE table_name = 'customers'" }],
  ['Types and info', 'Database version', 'Which version of the database software is running.', { sqlite: 'sqlite_version()', postgres: 'version()', mysql: 'VERSION()', mssql: '@@VERSION' }, { sqlite: 'SELECT sqlite_version() AS version', postgres: 'SELECT version()', mysql: 'SELECT VERSION() AS version', mssql: 'SELECT @@VERSION AS version' }],
  ['Types and info', 'EXPLAIN (how it runs)', 'Ask the database how it plans to find the answer. Useful when something is slow.', { sqlite: 'EXPLAIN QUERY PLAN SELECT ...', postgres: 'EXPLAIN SELECT ...', mysql: 'EXPLAIN SELECT ...', mssql: 'Use "Display Estimated Execution Plan" in SQL Server tools' }, { sqlite: "EXPLAIN QUERY PLAN SELECT * FROM orders WHERE customer_id = 5", postgres: 'EXPLAIN SELECT * FROM orders WHERE customer_id = 5', mysql: 'EXPLAIN SELECT * FROM orders WHERE customer_id = 5', mssql: '-- SQL Server: select the query in SSMS and press Ctrl+L' }]
];
function libPick(v) { if (typeof v === 'string') return v; const k = TW.adapter ? TW.adapter.kind : 'sqlite'; return v[k] ?? v.all ?? v.sqlite ?? Object.values(v)[0]; }
function adaptLimit(sql) {
  if (!TW.adapter || TW.adapter.kind !== 'mssql') return sql;
  const m = sql.match(/\s+LIMIT\s+(\d+)\s*;?\s*$/i);
  if (!m || /\bOFFSET\b/i.test(sql)) return sql;
  return sql.slice(0, m.index).replace(/^\s*SELECT\s+(DISTINCT\s+)?/i, (x, d) => `SELECT ${d || ''}TOP ${m[1]} `);
}
function libEntries() { return SQL_LIB.map(([cat, name, what, syntax, ex], i) => ({ i, cat, name, what, syntax: libPick(syntax), ex: adaptLimit(libPick(ex)) })); }
const SQL_KEYWORDS = ['SELECT', 'FROM', 'WHERE', 'AND', 'OR', 'NOT', 'IN', 'IS', 'NULL', 'LIKE', 'BETWEEN', 'EXISTS', 'JOIN', 'LEFT JOIN', 'RIGHT JOIN', 'INNER JOIN', 'FULL OUTER JOIN', 'CROSS JOIN', 'ON', 'AS', 'GROUP BY', 'ORDER BY', 'HAVING', 'LIMIT', 'OFFSET', 'DISTINCT', 'UNION', 'UNION ALL', 'INTERSECT', 'EXCEPT', 'CASE', 'WHEN', 'THEN', 'ELSE', 'END', 'ASC', 'DESC', 'WITH', 'RECURSIVE', 'OVER', 'PARTITION BY', 'INSERT INTO', 'VALUES', 'UPDATE', 'SET', 'DELETE FROM', 'CREATE TABLE', 'CREATE VIEW', 'CREATE INDEX', 'ALTER TABLE', 'ADD COLUMN', 'DROP TABLE', 'DROP COLUMN', 'PRIMARY KEY', 'FOREIGN KEY', 'REFERENCES', 'UNIQUE', 'DEFAULT', 'CHECK', 'BEGIN', 'COMMIT', 'ROLLBACK', 'TOP', 'COUNT(', 'SUM(', 'AVG(', 'MIN(', 'MAX(', 'ROUND(', 'UPPER(', 'LOWER(', 'LENGTH(', 'TRIM(', 'SUBSTR(', 'SUBSTRING(', 'REPLACE(', 'COALESCE(', 'NULLIF(', 'CAST(', 'ABS(', 'ROW_NUMBER() OVER (', 'RANK() OVER (', 'DENSE_RANK() OVER (', 'NTILE(', 'LAG(', 'LEAD(', 'FIRST_VALUE(', 'STRFTIME(', 'DATE(', 'JULIANDAY(', 'GROUP_CONCAT(', 'STRING_AGG(', 'CONCAT(', 'EXTRACT(', 'TO_CHAR(', 'DATE_FORMAT(', 'DATEADD(', 'DATEDIFF(', 'GETDATE()', 'CURRENT_DATE', 'NOW()', 'IIF('];
